# Mathematics Prep Course for Scientific Computing 2025/26

Author: Dr. Peter Münch, TU Berlin, 2025

## Introduction into NumPy

### Introduction

The goal of this task is to give a short introduction into NumPy and Jupyter notebooks. We will use Jupyter notebooks with Python throughout the class.

Some of you might already know NumPy from other classes (so that this task will be quite boring for you). For the others, who have used programming languages like `MATLAB`, `Julia`, or `R`, the transition should be rather simple since only the syntax changes slightly.

How to run Jupyter notebooks: execute one box at a time by clicking the play button next to the box and possibly add/modify code.

We start with importing the relevant libraries that we will need throughout this exercise.

In [29]:
import math
import numpy as np
import time



### Vectors and matrices



 In NumPy, Small vectors and arrays are created by converting the corresponding list or tuple with the function `np.array`. For example, to create the vector $v = \begin{bmatrix}3 & -1\end{bmatrix}$ and matrix $A = \begin{bmatrix}2 & -1 \\ -4 & 8\end{bmatrix}$:


In [30]:
v = np.array([3,-1])
v

array([ 3, -1])

In [31]:
A = np.array([[2,-1],[-4,8]])
A

array([[ 2, -1],
       [-4,  8]])

Note that a one-dimensional NumPy array is not represented as a matrix where one of the dimensions has the length 1 (unlike, for example, in Matlab) so that, in NumPy, you do not distinguish between row and column vectors.

You will now try a number of basic operations on the NumPy arrays `A` and `v`. Try to understand what each call does, for example, by performing the calculations by hand. Do the following:

In [32]:
A[0,1]

-1

In [33]:
A[0,:]

array([ 2, -1])

In [34]:
A.shape

(2, 2)

In [35]:
A.size

4

In [36]:
v.shape

(2,)

In [37]:
v.size

2

In [38]:
2*v

array([ 6, -2])

In [39]:
v+v

array([ 6, -2])

In [40]:
v*v

array([9, 1])

In [41]:
A*A

array([[ 4,  1],
       [16, 64]])

In [42]:
np.dot(v,v)

10

In [43]:
np.matmul(A,v)

array([  7, -20])

In [44]:
A @ v

array([  7, -20])

In [45]:
np.cos(A)

array([[-0.41614684,  0.54030231],
       [-0.65364362, -0.14550003]])

Also try `np.exp(A)`.

In [46]:
np.transpose(A)

array([[ 2, -4],
       [-1,  8]])

In [47]:
A.T

array([[ 2, -4],
       [-1,  8]])

Note: The usual mathematical operations `+`, `-`, `*`, `/` and `**` (power) on NumPy arrays  correspond to _elementwise operations_, i.e., they are performed on each element separately.

Task: now, perform a matrix-matrix multiplication $\begin{bmatrix}1 & 2 \\ 3 & 4\end{bmatrix}\begin{bmatrix}5 & 6 \\ 7 & 8\end{bmatrix}$ with NumPy. The result should be $\begin{bmatrix}19 & 22 \\ 43 & 50\end{bmatrix}$.

In [48]:
# TODO


#### Built-in operations to create vectors and matrices

Most often, NumPy is used to handle large vectors and matrices. Thus, it is inappropriate to use `np.array` to convert lists or tuples. Instead, it is preferred to use built-in functions provided by NumPy. Try the following features:

In [49]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

Also try `np.linspace(0,1,101)`. Why have we chosen 11 and 101 instead of 10 and 100?

In [50]:
np.arange(0,1,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [51]:
np.zeros(3)

array([0., 0., 0.])

Also try `np.zeros((5,5))`.

In [52]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [53]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [54]:
np.random.rand(4)

array([0.2321572 , 0.5610435 , 0.99241004, 0.32821619])

### Vectorization

Run the following code snippet. It performs a simple vector operation with a for-loop on a Python list (_non-vectorized code_) and with a NumPy array (_vectorized code_) and measures the running times. Try different sizes of the vector. Pay attention to differences in runtime and clarity of the code (i.e., how easy the code is to write and understand).

In [55]:
# Vector size
N = int(1e7)

# Python list
startTime_list = time.time()

x_list = list(range(N))
y_list = [math.sin(2*math.pi/N*x) for x in x_list]

endTime_list = time.time()

# Numpy array
startTime_arr = time.time()

x_arr = np.arange(0,N)
y_arr = np.sin(2*math.pi/N*x_arr)

endTime_arr = time.time()

print("Elapsed time with list: {:f} seconds\nElapsed time with NumPy array: {:f} seconds".format(endTime_list-startTime_list,endTime_arr-startTime_arr))

Elapsed time with list: 0.839693 seconds
Elapsed time with NumPy array: 0.045378 seconds


Note: _vectorization_ is not only referring to replacing for-loops by vector operations but also to rewriting your algorithm so that you can use the right dense linear-algebra routines referred to as BLAS (Basic Linear Algebra Subprograms) routines. These can be categorized as follows:
-  Level 1 BLAS: vector operations, e.g., $$y \gets \alpha x + y,$$
-  Level 2 BLAS: matrix-vector operations, e.g., $$y \gets \alpha A x + \beta y,$$
-  Level 3 BLAS: matrix-matrix operations, e.g., $$C \gets \alpha AB + \beta C.$$

These BLAS routines are highly optimized for most hardware architectures (e.g., SIMD vectorization, cache blocking) and as a result fast. The key message is: use built-in functions if possible.

### Testing

Throughout the course, you will need to implement different functions. We will help you by providing **tests**. Tests compare, for a given input, the output to an expected output.

Below, an example is given where a function `fu` is defined and tested.


In [56]:
def fu(values):
    return values * 2

input = np.array([0, 1, 2, 3])
output = np.array([0, 2, 4, 6])

assert np.all(np.isclose(fu(input), output))

Task: Now, change the functionality of `fu`. What happens!?

In [57]:
def fu(values):
    return values + 2
assert np.all(np.isclose(fu(input), output))

AssertionError: 

AssertionError shows the breakpoint for the error



### Outlook

Throughout the course, we will extensively use
- `matplotlib.pyplot.plot` for plotting of data
- `numpy.linalg.solve` or `scipy.linalg.solve` for solving of systems of linear equations
- `scipy.optimize.fsolve` for solving of systems of nonlinear equations

Please read up on these functionalities. Useful webpages are, e.g.:
- https://www.python.org/
- https://numpy.org/